
version: "3"

services:
  db:
    image: "mysql:5.6"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "mweike"
      MYSQL_USER: "weike"
      MYSQL_PASSWORD: "weike"
    ports:
      - "4306:3306"
    volumes: 
      - /Users/IT/proj/mweike/code/db:/docker-entrypoint-initdb.d
    networks:
      - app_net

  web:
    image: "itwk-php"
    ports:
      - "9080:80"
    volumes:
      - /Users/IT/proj/mweike/code/src:/var/www/html
      - ./config.inc.php:/var/www/html/config/config.inc.php
    networks:
      - app_net

networks:
  app_net:


# volumes:
#   itwk-store:

